[package]
name = "astracore_receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"  # latest stable version
dotenv = "0.15.0"
rand = "0.8"
tokio = { version = "1", features = ["full"] } # for async runtime