[package]
name = "astracore_receiver"
version = "1.0.0"
edition = "2025"

[dependencies]
actix-web = "4"  # latest stable version
dotenv = "0.15.0"
rand = "0.8"
tokio = { version = "1", features = ["full"] } # for async runtime
serde = { version = "1.0", features = ["derive"] }